openshift:
  templatePath: kube/template.yaml

maven:
  profileFeature: local
  profileDevelop:
  profileRelease:
  profileMaster:
  profileHotfix:

spring:
  profileFeature: dev
  profileDevelop: dev
  profileRelease: uat
  profileMaster: prod
  profileHotfix: uat

confirmDeploy:
  - develop
  - master
timeoutConfirmDeploy: true
timeoutConfirmDeployTime: 10
timeoutConfirmDeployUnit: SECONDS

testing:
  predeploy:
    unitTesting:
      - feature
      - develop
      - release
      - hotfix
    sonarQube:
      - feature
      - develop
      - release
      - hotfix
    checkstyle:
      # - feature
      # - develop
      # - release

  postdeploy:
    smokeTesting:
      - release
      - master
    securityTesting:
      - develop
      - release
    performanceTesting:
      - develop
      - release
      - hotfix
    acceptanceTesting:
      - develop
      - release

notifications:
  branch:
    - feature
    - develop
    - release
    - master
    - hotfix
type: slack

jenkins:
  maxOldBuildsToKeep: 5
  daysOldBuildsToKeep: 1
  errorOnPerformanceTestsUnstableResult: false